# M.6 -- minimal Claim model, kept strictly separate from Evidence. A Claim is a proposition an
# Evidence can SUPPORT/CONTRADICT/QUALIFY/CONTEXTUALIZE -- never the evidence itself. Separate
# sidecar (claims.json); never writes documents.json or statistical_evidence.json.
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
CLAIMS_PATH = HERE / "claims.json"
RELATIONS_PATH = HERE / "evidence_claim_relations.json"

CLAIM_TYPES = ("DESCRIPTIVE", "TREND", "CAUSAL", "PREDICTIVE", "NORMATIVE", "COMPARATIVE", "ATTRIBUTION")
CLAIM_STATUSES = ("OPEN", "SUPPORTED", "PARTIALLY_SUPPORTED", "CONTESTED", "WEAKENED",
                  "INSUFFICIENT_EVIDENCE", "REJECTED")
RELATION_TYPES = ("SUPPORTS", "CONTRADICTS", "QUALIFIES", "CONTEXTUALIZES", "INSUFFICIENT_FOR",
                  "NOT_RELEVANT")


def _claim_id(claim_text, topic):
    return f"claim_{hashlib.sha256(f'{topic}|{claim_text}'.encode()).hexdigest()[:16]}"


def new_claim(claim_text, topic, claim_type, scope=None, time_scope=None, geographic_scope=None,
              created_from=None, provenance=None):
    assert claim_type in CLAIM_TYPES, f"unknown claim_type: {claim_type!r}"
    return {
        "claim_id": _claim_id(claim_text, topic), "claim_text": claim_text, "topic": topic,
        "claim_type": claim_type, "scope": scope, "time_scope": time_scope,
        "geographic_scope": geographic_scope, "status": "OPEN",
        "created_from": created_from, "provenance": provenance,
        "created_at": datetime.now(timezone.utc).isoformat(),
    }


def new_relation(evidence_id, claim_id, relation_type, reason, provenance, strength="UNSPECIFIED"):
    """strength/status is never auto-generated by an LLM -- it is UNSPECIFIED unless a
    deterministic rule set it (e.g. a validated statistical observation directly matching the
    claim's time_scope and geographic_scope)."""
    assert relation_type in RELATION_TYPES, f"unknown relation_type: {relation_type!r}"
    relation_id = f"rel_{hashlib.sha256(f'{evidence_id}|{claim_id}|{relation_type}'.encode()).hexdigest()[:16]}"
    return {
        "relation_id": relation_id, "evidence_id": evidence_id, "claim_id": claim_id,
        "relation_type": relation_type, "strength": strength, "reason": reason,
        "provenance": provenance, "created_at": datetime.now(timezone.utc).isoformat(),
    }


def _load(path):
    return json.loads(path.read_text(encoding="utf-8")) if path.exists() else {}


def _save(path, data):
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def upsert_claim(claim):
    claims = _load(CLAIMS_PATH)
    existing = claims.get(claim["claim_id"])
    if existing:
        claim["created_at"] = existing["created_at"]  # identity-stable: never overwrite creation time
    claims[claim["claim_id"]] = claim
    _save(CLAIMS_PATH, claims)
    return claim


def upsert_relation(relation):
    relations = _load(RELATIONS_PATH)
    relations[relation["relation_id"]] = relation
    _save(RELATIONS_PATH, relations)
    return relation


def load_claims():
    return _load(CLAIMS_PATH)


def load_relations():
    return _load(RELATIONS_PATH)
