"""METAXIS Operator reader-layer postprocessor.

Python automatically imports sitecustomize from the script directory.  When operator_ui.py is
run by the existing GitHub Actions build, this module registers an atexit pass over the generated
PRIVATE Operator HTML only.  It never touches site/ or metaxis.kr.

Purpose:
- keep canonical Intelligence JSON/internal enums untouched;
- make Operator Intelligence/Report pages Korean-first and readable;
- remove raw engineering vocabulary from reader-facing labels;
- fix the Reports list so it opens the already-generated Operator report inspector instead of
  escaping to the sibling /intelligence route;
- keep source title + original URL visible at the bottom of report pages.
"""
from __future__ import annotations

import atexit
import os
import re
import sys
from pathlib import Path


def _is_operator_build() -> bool:
    return bool(sys.argv and Path(sys.argv[0]).name == "operator_ui.py")


# Reader-facing translation only. Canonical data is deliberately not mutated.
_TEXT = {
    "Intelligence Portfolio / 인텔리전스 포트폴리오": "인텔리전스",
    "확정 인텔리전스 / Confirmed Intelligence": "정식 인텔리전스",
    "Intelligence Candidates": "인텔리전스 후보",
    "Intelligence 변화 가능성 / Judgment-Change Watch": "판단 변화 관측",
    "반증 자료 (Counterevidence)": "반대 근거",
    "Inspect": "상세 분석",
    "Full Report": "전체 보고서",
    "Report Inspector": "인텔리전스 상세 분석",
    "Current State": "현재 판단",
    "Hypotheses (canonical status)": "검토 중인 가설",
    "Claims (Key Claims)": "핵심 판단과 주장",
    "근거 / Research Evidence": "핵심 근거",
    "Statistics": "통계·지표",
    "Observation": "관측값",
    "Forecast": "전망",
    "반증 자료 / Counterevidence": "반대 근거",
    "Alternative Explanations": "다른 설명 가능성",
    "Geographic Applicability": "지역별 적용 범위",
    "Temporal Applicability": "시간적 적용 범위",
    "Known Gaps": "아직 확인이 필요한 부분",
    "Reports (version history)": "보고서 변경 이력",
    "Version Diffs (via report_engine.diff_reports())": "이전 버전과 달라진 점",
    "Provenance": "근거 추적",
    "Sources (출처)": "출처 및 참고자료",
    "Sources (출처) --": "출처 및 참고자료 —",
    "actually used": "실제 사용",
    "Source": "출처",
    "Institution": "기관",
    "Title": "자료 제목",
    "Year": "연도",
    "Tier": "출처 등급",
    "Access Status": "접근 상태",
    "Real URL": "원문 링크",
    "Link Verification": "링크 확인",
    "Readiness": "분석 상태",
    "Generated": "생성일",
    "Version": "버전",
    "Claims": "주장",
    "Hypotheses": "가설",
    "Evidence": "근거",
    "Detail": "상세",
    "Latest Report Version": "최신 보고서",
    "Updated": "갱신일",
    "Topic": "주제",
    "IO Version": "분석 버전",
    "Evidence Snapshot": "근거 스냅샷",
    "Canonical Status": "현재 상태",
    "Statement": "내용",
    "Code": "구분",
    "CONDITIONALLY_READY": "조건부 분석 가능",
    "READY": "분석 가능",
    "AVAILABLE": "확인됨",
    "NOT_AVAILABLE": "자료 부족",
    "UNKNOWN": "미확인",
    "MATCHED": "근거 일치",
    "PARTIAL_MATCH": "일부 일치",
    "OUT_OF_SCOPE": "분석 범위 밖",
    "SUPPORTING": "지지 근거",
    "CONTRADICTING": "반대 근거",
    "OBSERVATION": "관측",
    "FORECAST": "전망",
    "DERIVATIVE_REPORTING": "2차 보도",
    "PRIMARY": "1차 자료",
    "RESEARCH": "연구자료",
    "NEWS": "보도자료",
    "USA": "미국",
    " US ": " 미국 ",
    " KR ": " 한국 ",
    " CN ": " 중국 ",
    " EU ": " 유럽연합 ",
    " IE ": " 아일랜드 ",
}

# Internal field names occasionally leak because canonical content blocks are rendered as dicts.
# Translating the keys makes the evidence legible without changing the evidence value itself.
_FIELD = {
    "event_country": "사건 발생 국가",
    "publisher_country": "발행기관 국가",
    "source_registry_verified_publisher_country": "확인된 발행기관 국가",
    "temporal_type": "시간 구분",
    "claim_id": "근거 식별자",
    "hypothesis_id": "가설 식별자",
    "source_id": "출처 식별자",
    "evidence_independence": "근거 독립성",
    "observation_or_forecast": "관측/전망",
    "access_status": "접근 상태",
    "rights_status": "이용 상태",
    "verification": "검증 상태",
}


def _translate_html(text: str) -> str:
    # Fix Reports route first. /operator/reports/ -> /operator/report/{id}/ is inside the same
    # Cloudflare-protected Operator tree and is already generated by operator_ui.py.
    text = text.replace('href="../../intelligence/', 'href="../report/')
    text = text.replace("href='../../intelligence/", "href='../report/")

    # Reader-facing phrases.
    for src, dst in sorted(_TEXT.items(), key=lambda kv: len(kv[0]), reverse=True):
        text = text.replace(src, dst)
    for src, dst in sorted(_FIELD.items(), key=lambda kv: len(kv[0]), reverse=True):
        text = text.replace(src, dst)

    # Remove the most distracting engineering-only explanations from reader pages while retaining
    # underlying evidence text and links. These are display-only removals, not data deletion.
    text = re.sub(r'<p class="empty">No overall quality score.*?</p>', '', text, flags=re.S)
    text = text.replace('(Claim/IO 아님, Evidence Quality:', '(아직 정식 인텔리전스로 승격되지 않음 · 근거 수준:')
    text = text.replace('Claim/IO 아님', '분석 후보')
    text = text.replace('Evidence Quality:', '근거 수준:')
    text = text.replace('Current status:', '현재 상태:')
    text = text.replace('Contradicting evidence:', '반대 근거:')

    # English-only empty states.
    text = text.replace('No hypotheses recorded for this topic.', '현재 등록된 가설이 없습니다.')
    text = text.replace('No independently-cited real-URL sources recorded for this report version.',
                        '이 보고서 버전에 연결된 독립 원문 출처가 없습니다.')
    text = text.replace('empty / 자료 부족', '현재 표시할 근거가 없습니다.')
    text = text.replace('none', '없음')

    # Make source heading contract explicit at the end of report pages.
    text = text.replace('<h3>출처 및 참고자료 --', '<h3>출처 및 참고자료 —')
    return text


def _postprocess() -> None:
    if not _is_operator_build():
        return
    # Existing workflow passes intel_private/ as argv[1]. Resolve relative to repository cwd.
    out = Path(sys.argv[1] if len(sys.argv) > 1 else "intel_private")
    if not out.is_absolute():
        out = Path.cwd() / out
    if not out.exists():
        return

    targets = []
    # Operator navigation + report inspector pages.
    op_dir = out / "operator"
    if op_dir.exists():
        targets.extend(op_dir.rglob("*.html"))
    # The sibling full-report pages can still be reached by old bookmarks; Koreanize them too.
    intel_dir = out / "intelligence"
    if intel_dir.exists():
        targets.extend(intel_dir.rglob("*.html"))

    for path in targets:
        try:
            old = path.read_text(encoding="utf-8")
            new = _translate_html(old)
            if new != old:
                path.write_text(new, encoding="utf-8")
        except Exception as exc:  # fail-soft: never break the scheduled build
            print(f"[operator-reader-layer] {path}: {exc}", file=sys.stderr)


if _is_operator_build():
    atexit.register(_postprocess)
